### ISSUE TITLE
add some more songs in it!

### ISSUE THREAD

**Issue by kirtiraj22** [kirtiraj22/music-player#1]

**Comment by davidjs11** [comment]
could you please assign it to me?

**Comment by kirtiraj22** [comment]
ok @davidjs11 you can work on it!
make sure to star this repo and follow me.
and do checkout the contribution guidelines!

**Comment by aman999au** [comment]
Can you assign it to me

**Comment by kirtiraj22** [comment]
yaa @Aman0786-git even you can work on it!
make sure to star this repo and follow me!

**Comment by Yash636261** [comment]
assigen it to me want to add more songs.

**Comment by kirtiraj22** [comment]
> assigen it to me want to add more songs.

Done!

**Comment by mohitparmar1** [comment]
Bhai mujhe bhi assigen krdo task

**Comment by kirtiraj22** [comment]
> Bhai mujhe bhi assigen krdo task

Done!
