### ISSUE TITLE
change the screenshots in README.md file

### ISSUE THREAD

**Issue by kirtiraj22** [kirtiraj22/music-player#25]

**Comment by abhi87374** [comment]
please assign this task to me ...

**Comment by abhi87374** [comment]
and please tell me something about the new screenshot...

**Comment by kirtiraj22** [comment]
alright @abhi87374 you can work on it!
you just need to take 2-3 screenshots of the music-player, crop it and then upload those screenshots in README file by storing them in folder named as screenshots

**Comment by komalioruganti** [comment]
Can I work on this as well?

**Comment by kirtiraj22** [comment]
@komalioruganti alright i will assign it to you too!

now this will be first come first serve!

**Comment by komalioruganti** [comment]
Should I add screenshots of all the songs or only a few?
